### ISSUE TITLE
反馈个小问题

### ISSUE THREAD

**Issue by deaeB** [HCKxv/DSP-Blueprint-of-HCK#1]
2-消耗品/前期100透镜 这里有一节垂直传送带我拍下来是断开的
![conveyor](https://github.com/user-attachments/assets/b214d246-216d-404c-96aa-8f7d4761b98c)

不清楚是版本还是纬度问题,我也不懂仙术,总之手动接上之后保存蓝图原地再拍依旧是断开的, 应该是断点处横着的那条一般通过蓝带导致的,把那条删掉再拍就正常了

**Comment by HCKxv** [comment]
这里确实有问题，修复版已上传
